import type { NextPage } from "next";
import Head from "next/head";
import { useMediaQuery } from "react-responsive";
import ApplyNow from "../components/ApplyNow/ApplyNow";
import Button from "../components/Button/Button";
import HeaderDesktop from "../components/Header/desktop/Header";
import Header from "../components/Header/Header";
import HeaderMobile from "../components/Header/mobile/Header";
import HeroBanner from "../components/HeroBanner/HeroBanner";
import Steps from "../components/Steps/Steps";
import TopBar from "../components/TopBar/TopBar";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
    const isLg = useMediaQuery({ query: "(min-width: 992px)" });
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Header />
                {/*                 <TopBar
                    text="We have 100+ open positions"
                    linkText="Join Us"
                    linkHref="#career"
                />
                <HeroBanner />
                <Steps /> 
                <ApplyNow />*/}
            </main>
        </div>
    );
};

export default Home;
