import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button/Button";
import Header from "../components/Header/Header";
import HeroBanner from "../components/HeroBanner/HeroBanner";
import Steps from "../components/Steps/Steps";
import TopBar from "../components/TopBar/TopBar";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <TopBar
                    text="We have 100+ open positions"
                    linkText="Join Us"
                    linkHref="#career"
                />
                <Header />
                <HeroBanner />
                <Steps />
            </main>
        </div>
    );
};

export default Home;
